apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sveggalam/ApplicationCD.git
    targetRevision: HEAD
    path: studentDeployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
