apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: sveggalam/fullstack:library 
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"

