apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library
  ports:
    - name: http
      port: 8082         # Service port
      targetPort: 8082   # Container port
      nodePort: 30082    # Node port (range 30000–32767)
